 CREATE DATABASE mydb;

  SHOW DATABASES; 


 CREATE TABLE employee(id INTEGER AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,age VARCHAR(100) NOT NULL ,country VARCHAR(100) NOT NULL,email VARCHAR(100) NOT NULL,Mobile VARCHAR(100) NOT NULL; 

  DESC employee